image: node:8

# Set up MySQL test-database
services:
  - mysql:5.5

# Configure test-database
variables:
  MYSQL_DATABASE: supertestdb
  MYSQL_ROOT_PASSWORD: secret

cache:
  paths:
     - node_modules

stages:
  - test
  - pages


# Install node libraries
before_script:
  - cd backend && npm install

# Run JEST tests
run_tests:
  stage: test
  script:
    - npm test
  artifacts:
    paths:
      - backend/coverage/

before_script:
  - cd backend && npm install


# Publish coverage report on gitlab-pages
pages:
  stage: pages
  dependencies:
    - run_tests
  script:
    - npm install
    - mkdir .public
    - ls
    - cp -r coverage/* .public
    - mv .public public
  artifacts:
    paths:
      - coverage
